// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCIylXeCQdawH_S5tl3A0KjPzSYYVP0sdQ',
    appId: '1:689825329356:web:877999f17715d145b69269',
    messagingSenderId: '689825329356',
    projectId: 'tcm-db-2e5b3',
    authDomain: 'tcm-db-2e5b3.firebaseapp.com',
    storageBucket: 'tcm-db-2e5b3.firebasestorage.app',
    measurementId: 'G-G33Y0Z7K6E',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCi9tnuMROsnPnNWb73lIH2vUulK6L7BEM',
    appId: '1:689825329356:android:b2913131c4932b11b69269',
    messagingSenderId: '689825329356',
    projectId: 'tcm-db-2e5b3',
    storageBucket: 'tcm-db-2e5b3.firebasestorage.app',
  );

  // iOS/macOS are not actually configured yet: this project (tcm-db-2e5b3) has no
  // matching GoogleService-Info.plist / iOS Firebase App. If needed, run
  // `flutterfire configure --project=tcm-db-2e5b3` and select the ios platform to
  // generate real apiKey/appId values. Do not substitute credentials from another
  // project, or it will reproduce the "connected to the wrong database" bug.
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCi9tnuMROsnPnNWb73lIH2vUulK6L7BEM',
    appId: '1:689825329356:android:b2913131c4932b11b69269',
    messagingSenderId: '689825329356',
    projectId: 'tcm-db-2e5b3',
    storageBucket: 'tcm-db-2e5b3.firebasestorage.app',
    iosBundleId: 'my.edu.tarumt.tcmApp',
  );
  static const FirebaseOptions macos = ios;

  static const FirebaseOptions windows = web;
}
